AnonSend/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('upload_success', views.uploaded_link, name="upload_success"),
    path('faq', views.faq, name="faq"),
    path('p/<public_link>', views.public_link_handle, name="public_link"),
    path('analytics/<analytic_link>', views.analytic_link_handle, name="analytic_link"),
    path('csv/<analytic_link>', views.downloadAsCsv, name="download_csv"),
    path('report/<public_link>', views.report_link, name="report_link")
]

main/models.py
from django.db import models

from main.helper import gen_link, gen_analytic_link

REPORT_CHOICES = [
    ("malicious", "Malicious file"),
    ("inappropriate", "Inappropriate / Illegal Content"),
    ("dmca", "DMCA violation"),
]


class UploadFile(models.Model):
    # Uniquely random fields
    public_link = models.CharField(max_length=15, primary_key=True, default=gen_link)
    analytic_link = models.CharField(max_length=15, unique=True, default=gen_analytic_link)

    # Form inputs
    file = models.FileField(upload_to="uploaded_files/")
    password = models.CharField(max_length=100, blank=True)
    expires_at = models.DateTimeField(verbose_name="Expires in")
    max_downloads = models.PositiveSmallIntegerField(default=1, choices=[(i, i) for i in range(1, 11)])

    # Derived fields
    file_hash = models.CharField(max_length=41, )
    file_name = models.CharField(max_length=40)

    def __str__(self):
        return self.public_link

    def expiry(self):
        return self.expires_at


class Analytic(models.Model):
    upload_file = models.ForeignKey(UploadFile, on_delete=models.CASCADE)

    # From user-agent
    os = models.CharField(max_length=40, default="Unknown")
    device_type = models.CharField(max_length=40, default="Unknown")
    browser = models.CharField(max_length=40, default="Unknown")

    # From ip
    country = models.CharField(max_length=40, default="Unknown")

    time_clicked = models.DateTimeField(auto_now_add=True)


class ReportLink(models.Model):
    upload_file = models.ForeignKey(UploadFile, on_delete=models.CASCADE)
    reason = models.CharField(max_length=10, choices=REPORT_CHOICES, default=REPORT_CHOICES[0])
    description = models.TextField(max_length=150)
    report_time = models.DateTimeField(auto_now_add=True)

templates/analytics.html
<html>
<head>

    <meta charset="UTF-8"/>
    <title>Analytics</title>
    <!-- Resources -->
    <script src="https://www.amcharts.com/lib/4/core.js"></script>
    <script src="https://www.amcharts.com/lib/4/maps.js"></script>
    <script src="https://www.amcharts.com/lib/4/charts.js"></script>
    <script src="https://www.amcharts.com/lib/4/geodata/worldLow.js"></script>
    <script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>

    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link type="text/css" rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!-- Chart code -->
    <script>
        function downloadAsCsv() {
            let btn = document.getElementById('submit');
            btn.classList.remove("btn-primary");
            btn.classList.add("btn-success");
        }

        am4core.ready(function () {
// Themes begin
            am4core.useTheme(am4themes_animated);
// Themes end

            var chart = am4core.create("piediv1", am4charts.PieChart);
            chart.hiddenState.properties.opacity = 0; // this creates initial fade-in

            {#chart.legend = new am4charts.Legend();#}

            chart.data = [

                {% for k,v in device_type %}
                    {
                        device: "{{ k }}",
                        frequency: "{{ v }}"
                    },
                {% endfor %}

            ];

            var series = chart.series.push(new am4charts.PieSeries());
            series.dataFields.value = "frequency";
            series.dataFields.category = "device";

            var chart = am4core.create("piediv2", am4charts.PieChart);
            chart.hiddenState.properties.opacity = 0; // this creates initial fade-in

            {#chart.legend = new am4charts.Legend();#}

            chart.data = [
                {% for k,v in browser %}
                    {
                        browser: "{{ k }}",
                        frequency: "{{ v }}"
                    },
                {% endfor %}
            ];

            var series = chart.series.push(new am4charts.PieSeries());
            series.dataFields.value = "frequency";
            series.dataFields.category = "browser";
            // Create map instance
            var chart = am4core.create("mapdiv", am4maps.MapChart);

// Set map definition
            chart.geodata = am4geodata_worldLow;

// Set projection
            chart.projection = new am4maps.projections.Miller();

// Create map polygon series
            var polygonSeries = chart.series.push(new am4maps.MapPolygonSeries());
            polygonSeries.exclude = ["AQ"];

//Set min/max fill color for each area
            polygonSeries.heatRules.push({
                property: "fill",
                target: polygonSeries.mapPolygons.template,
                min: chart.colors.getIndex(1).brighten(1),
                max: chart.colors.getIndex(1).brighten(-0.3)
            });


// Make map load polygon data (state shapes and names) from GeoJSON
            polygonSeries.useGeodata = true;

// Set heatmap values for each state
            polygonSeries.data = [
                {% for k,v in country %}
                    {
                        id: "{{ k }}",
                        value:{{ v }}
                    },
                {% endfor %}
            ];
// Set up heat legend
            let heatLegend = chart.createChild(am4maps.HeatLegend);
            heatLegend.series = polygonSeries;
            heatLegend.align = "right";
            heatLegend.valign = "bottom";
            heatLegend.width = am4core.percent(20);
            heatLegend.marginRight = am4core.percent(4);
            heatLegend.minValue = 0;
            heatLegend.maxValue = 40000000;

// Set up custom heat map legend labels using axis ranges
            var minRange = heatLegend.valueAxis.axisRanges.create();
            minRange.value = heatLegend.minValue;
            minRange.label.text = "Little";
            var maxRange = heatLegend.valueAxis.axisRanges.create();
            maxRange.value = heatLegend.maxValue;
            maxRange.label.text = "A lot!";

// Blank out internal heat legend value axis labels
            heatLegend.valueAxis.renderer.labels.template.adapter.add("text", function (labelText) {
                return "";
            });

// Configure series tooltip
            var polygonTemplate = polygonSeries.mapPolygons.template;
            polygonTemplate.tooltipText = "{name}: {value}";
            polygonTemplate.nonScalingStroke = true;
            polygonTemplate.strokeWidth = 0.5;

// Create hover state and set alternative fill color
            var hs = polygonTemplate.states.create("hover");
            hs.properties.fill = am4core.color("#3c5bdc");
            // Zoom control;
            chart.zoomControl = new am4maps.ZoomControl();

            var homeButton = new am4core.Button();
            homeButton.events.on("hit", function () {
                chart.goHome();
            });

            homeButton.icon = new am4core.Sprite();
            homeButton.padding(7, 5, 7, 5);
            homeButton.width = 30;
            homeButton.icon.path = "M16,8 L14,8 L14,16 L10,16 L10,10 L6,10 L6,16 L2,16 L2,8 L0,8 L8,0 L16,8 Z M16,8";
            homeButton.marginBottom = 10;
            homeButton.parent = chart.zoomControl;
            homeButton.insertBefore(chart.zoomControl.plusButton);
        }); // end am4core.ready()
    </script>
    <style>
        body {
            background: #9053c7;
            background: -webkit-linear-gradient(-135deg, #c850c0, #4158d0);
            background: -o-linear-gradient(-135deg, #c850c0, #4158d0);
            background: -moz-linear-gradient(-135deg, #c850c0, #4158d0);
            background: linear-gradient(-135deg, #c850c0, #4158d0);
        }
    </style>

</head>
<!-- HTML -->
<body>

<div class="d-flex w-100 p-3">
    {% include 'header.html' %}
</div>
<div class="container">
    <div class="bg-white py-2 px-4 m-3 rounded 2-">
        <div class="row">
            <p class="h2">Geolocation Statistics:</p>
        </div>
        <div id="mapdiv" class="row h-50"></div>
    </div>
    <div class="bg-white py-2 px-4 m-3 rounded">
        <div class="row">
            <p class="h2">Device Statistics: </p>
        </div>
        <div class="row ">
            <div id="piediv1" class="col-6" style="height: 300px;width: 640px;"></div>
            <div id="piediv2" class="col-6" style="height: 300px;width: 640px;"></div>
        </div>
    </div>
    <div class="bg-white py-2 px-4 m-3 rounded ">
        <div class="row">
            <p class="h2">Detailed Statistics:</p>
        </div>
        <div class="row d-none d-md-block d-lg-block">
            <table class="table ">
                <tr>
                    <th>Time</th>
                    <th>Operating System</th>
                    <th>Device Type</th>
                    <th>Browser</th>
                    <th>Country</th>
                </tr>
                {% for record in results|slice:":10" %}
                    <tr>
                        <td>
                            {{ record.time_clicked }}
                        </td>
                        <td>
                            {{ record.os }}
                        </td>
                        <td>
                            {{ record.device_type }}
                        </td>
                        <td>
                            {{ record.browser }}
                        </td>
                        <td>
                            {{ record.country }}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <a id="submit" onclick="downloadAsCsv();" href="/csv/{{ link }}" class="btn btn-primary m-3">Download as
            csv</a>
    </div>
</div>
</body>
</html>

templates/faq.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load myfilters %}
    <title>AnonSend - FAQ</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <script src="{% static 'js/jquery-3.2.1.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.js' %}" type="text/javascript"></script>
    <style>
        body {
            background: #9053c7;
            background: -webkit-linear-gradient(-135deg, #c850c0, #4158d0);
            background: -o-linear-gradient(-135deg, #c850c0, #4158d0);
            background: -moz-linear-gradient(-135deg, #c850c0, #4158d0);
            background: linear-gradient(-135deg, #c850c0, #4158d0);
        }
    </style>
</head>
<body class="px-2">

<div class="d-flex w-100 p-3">
    {% include 'header.html' %}
</div>
<div class="m-auto container bg-light p-5 " style="border-radius: 10px">
    <div class="panel-group" id="accordion">
        {% for question,answer in questions.items %}
            <div class="panel panel-default my-2">
            <div class="panel-heading">
                <div class="panel-title">
                    <a class="h4 btn-link" data-toggle="collapse" data-parent="#accordion"
                        href="#collapse{{ forloop.counter }}">
                        {{ question }}
                    </a>
                </div>
                <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse in">
                    <div class="panel-body">
                        <h5>{{ answer }}</h5>
                    </div>
                </div>
            </div>
        {% endfor %}

        </div>
    </div>
</bodyc>
</html>

templates/header.html
<div class="d-block w-100 fadeInDown" style="animation-duration: 1s">
    <a href="/" class="d-inline-block">
        <h1 class="text-light"><strong>Anon</strong>Send</h1>
    </a>
    <a href="{% url 'faq' %}" class="text-light float-right h3 mt-2" >FAQ</a>
    <hr class="bg-light"/>
</div>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load myfilters %}
    <title>AnonSend - File Share</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body class="container-login100">
<div class="limiter">
    {% include 'header.html' %}
    <div class="d-flex w-100 align-items-center justify-content-center " style="min-height: 89vh">
        <div class="wrap-login100 pt-4">
            <div class="login100-pic js-tilt" data-tilt>
                <img class="mt-3" src="{% static 'images/upload.svg' %}" alt="IMG">
            </div>


            <form class="login100-form validate-form" method="POST" enctype="multipart/form-data"
                  action="{% url 'upload_success' %}">
                {% csrf_token %}
                <span class="login100-form-title mb-2">
						Upload your files
					</span>
                <div class="wrap-input100">
                    <h5>{{ form.visible_fields.0.label_tag }}</h5>
                    <input onchange="validateSize()" type="file" name="file" multiple="" class="form-control-file" required="" id="id_file">
                </div>

                <div class="wrap-input100">
                    <h5>{{ form.visible_fields.1.label_tag }}</h5>
                    {{ form.visible_fields.1|addclass:"custom-select" }}

                </div>
                <div class="wrap-input100">
                    <h5>{{ form.visible_fields.2.label_tag }}</h5>
                    {{ form.visible_fields.2|addclass:"custom-select" }}
                </div>
                <div class="wrap-input100">
                    <h5>{{ form.visible_fields.3.label_tag }}</h5>
                    {{ form.visible_fields.3|addclass:"form-control" }}
                </div>
                <div class="container-login100-form-btn">
                    <input class="login100-form-btn" value="Upload" type="submit"/>
                </div>
            </form>
        </div>
    </div>
</div>


<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/tilt.jquery.min.js' %}"> $('.js-tilt').tilt({
    reset: false, scale: 1.1
})
</script>
<script>
    function validateSize() {
        const fileElem = document.getElementById('id_file');
        let total = 0;
        let f;
        for (f of fileElem.files) {
            total += f.size;
        }
        if (total > 104857600) {
            alert("File size limit exceeded");
        }
    }
</script>
</body>
</html>

templates/public_link.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load myfilters %}
    <meta charset="UTF-8"/>
    <title>Download Files</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body class="container-login100 d-block">
{% include 'header.html' %}
<div class="container-login100 justify-content-center">

    <div class="wrap-login100">
        <div class="login100-pic js-tilt m-4" data-tilt>
            <img src="{% static "images/download.svg" %}">
        </div>
        <div class="login100-form my-auto">
            <span class="login100-form-title mb-4">Download Files</span>
            <h5>Download your files using AnonSend.Fast, Simple, and Secure</h5>
            <form method="post" class="login100-form" onsubmit="submitForm()">
                <div class="form-group mt-3">
                    {% csrf_token %}
                    {% if form.expected_password %}
                        <div class="wrap-input100">

                            {% for field in form.visible_fields %}
                                {{ field.label_tag }}
                                {% with "form-control "|add:valid as tmp_class %}
                                    {{ field|addclass:tmp_class }}
                                {% endwith %}
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <input type="submit" class="login100-form-btn btn-dark" value="Download" id="submit"/>
            </form>
            <div class="text-center mt-2">
                <a class="txt2" href="javascript:void(0)" onclick="genReportLink()">Report file</a>
            </div>
        </div>
    </div>

</div>
<script>
    function genReportLink() {
        // Return the public link
        // domain.com/p/<public_link>
        // Concat 'report/' to it
        window.location.href = "/report/" + window.location.pathname.split('/')[2];

    }

    function submitForm() {
        let submit = document.getElementById('submit');
        submit.disabled = true;
        submit.classList.add('bg-dark');
        let input = document.getElementById('id_password');
        input.classList.remove('is-invalid');
        input.classList.add("is-valid");
    }

</script>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/tilt.jquery.min.js' %}"> $('.js-tilt').tilt({
    reset: false, scale: 1.1
})
</script>
</body>


</html>

templates/report_link.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load myfilters %}
    <title>AnonSend - Report Links</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <script src="{% static 'js/nicEdit-latest.js' %}" type="text/javascript">
    </script>
</head>
<body class="container-login100 d-block">

{% include 'header.html' %}

<div class="container-login100 justify-content-center">
    <div class="wrap-login100 justify-content-lg-around">
        <span class="login100-form-title mb-2">Report Link</span>
        <form method="POST" action="#">
            {% csrf_token %}
            <div class="form-group">
                <h5 class="my-2 font-weight-bold">{{ report_form.visible_fields.0.label_tag }}</h5>
                {{ report_form.visible_fields.0 }}
            </div>
            <div class="form-group">
                <h5 class="my-2 font-weight-bold">{{ report_form.visible_fields.1.label_tag }}</h5>
                <div class="border border-dark">
                    {{ report_form.visible_fields.1 }}
                </div>
            </div>
            <span class="wrap-input100"></span>
            <input type="submit" class="login100-form-btn" value="Submit"
                   onclick="nicEditors.findEditor('id_description').saveContent();">
        </form>
    </div>
</div>
<script type="text/javascript">
    function showEditor() {
        if (window.innerWidth > 768) {
            var elem = document.getElementById("id_description");
            elem.cols = 40;
            elem.rows = 7;
            bkLib.onDomLoaded(nicEditors.allTextAreas);
        }
    }

    showEditor();
</script>
</body>
</html>

templates/report_link.success.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load myfilters %}
    <title>AnonSend - File Share</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body class="container-login100 d-block">
{% include 'header.html' %}
<div class="container-login100 justify-content-center">
    <div class="wrap-login100">
        <div class="login100-pic mt-1">
            <img src="{% static 'images/sad.svg' %}"/>
        </div>
        <div class=" login100-form">
            <span class="login100-form-title mb-3">Reported Successfully</span>
            <h5 class="m-3">
                We regret the inconvenience caused. We will start working on it right away.
            </h5>
            <a href="/" class="login100-form-btn mt-4">Back to Homepage</a>
        </div>
    </div>
</div>
</body>
</html>

templates/size_limit.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>404</title>
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link type="text/css" rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>

<body class="container-login100 d-block ">
{% include 'header.html' %}
<div class="container-login100 justify-content-center">

    <div class="wrap-login100 justify-content-center">
        <img src="{% static "images/big.svg" %}" class="w-50 my-2">
        <span class="login100-form-title my-2">File too big</span>
        <h5 class="mb-2">Currently we only support files less than 100MB for each link</h5>
        <a class="login100-form-btn my-2" href="/">Go to Homepage</a>
    </div>
</div>
</body>

</html>

templates/upload_success.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Upload Success</title>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static "js/bootstrap.bundle.js" %}"></script>
    <script src="{% static "js/qrcode.min.js" %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

</head>

<body class="container-login100 d-block ">

{% include 'header.html' %}

<div class="container-fluid d-flex">

    <div class="wrap-login100 fadeInLeft mx-auto" style="animation-duration: 1s">
        <div class="login100-pic js-tilt mt-0" data-tilt>
            <img src="{% static "images/mobile_testing.svg" %}" alt="Public Link Image">
        </div>
        <div class="login100-form">
            <span class="login100-form-title">Public Link </span>
            <p>This is the public link for your files.<strong>The other person must
                require
                this to be
                able download your file(s)</strong>. It remains active for the specified amount of time and
                number
                of downloads.If you have set a password, the opposing person must submit the same password
                before
                they are allowed to download the file(s).
            </p>
            <label for="public"></label>

            <div class="d-flex">
                <input readonly class="form-control p-2 m-2 w-75" id="public"
                       value="http://127.0.0.1:8000/p/{{ public_link }}" onclick="this.select();"
                />

                <img class="my-3" alt="Copy to clipboard" onclick="copy_to_clipboard('public')"
                     src="{% static "images/clippy.svg" %}" style="width: 30px;height:30px"
                     title="Copy to clipboard">
                <img class="my-3 ml-1"
                     alt="Show QR"
                     title="QR Code"
                     src="{% static "images/qr.svg" %}"
                     style="width: 30px;height:30px"
                     data-toggle="popover"
                     data-content="
                            <div id='qr_pub' style=''></div>
                            <script>
                                      new QRCode(document.getElementById('qr_pub'), 'http://127.0.0.1:8000/{{ public_link }}');
                            </script>"
                />

            </div>
        </div>
    </div>

</div>

<hr class="bg-light"/>
<div class="container-fluid d-flex ">
    <div class="wrap-login100 fadeInRight mx-auto" style="animation-duration: 1s">
        <div class="login100-pic js-tilt" data-tilt>
            <img src="{% static "images/all_the_data.svg" %}"
                 alt="Analytic link image"/>
        </div>
        <div class="login100-form">
            <span class="login100-form-title">Analytic Link </span>
            <p>
                This is the analytic link. You can use this link to view a dashboard that displays various
                statistics corresponding to the public link. Statistics collected include device type,
                country,
                time
                of download and much more.<strong>The other person need not require this link</strong> to
                download
                the files. Your analytic link will expire after the time period you specified during
                uploading
                the
                file(s).
            </p>
            <label for="analytic"></label>
            <div class="d-flex">

                <input readonly
                       class="form-control p-2 m-2 w-75"
                       id="analytic" value="http://127.0.0.1:8000/analytics/{{ analytic_link }}"
                       onclick="this.select();"
                />
                <img src="{% static "images/clippy.svg" %}"
                     class="my-3"
                     style="width: 30px;height:30px"
                     title="Copy to clipboard"
                     onclick="copy_to_clipboard('analytic');"
                     alt="Copy to clipboard"/>

                <img class="my-3 ml-1"
                     alt="Show QR"
                     title="QR Code"
                     src="{% static "images/qr.svg" %}"
                     style="width: 30px;height:30px"
                     data-toggle="popover"
                     data-content="
                        <div id='qr_analytic' style=''></div>
                        <script>
                        new QRCode(document.getElementById('qr_analytic'), 'http://127.0.0.1:8000/analytics/{{ analytic_link }}');
                      </script>"
                />
            </div>
        </div>
    </div>
</div>


</body>
<script>
    $(function () {
        $('[data-toggle="popover"]').popover({
            html: true,
        })
    });

    function copy_to_clipboard(btn_type) {
        let text = document.getElementById(btn_type);
        text.select();
        document.execCommand("copy");
    }
</script>

<script src="{% static 'js/tilt.jquery.min.js' %}"> $('.js-tilt').tilt({
    reset: false, scale: 1.1
})
</script>

</html>